In [18]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split

data = pd.read_csv('classification2.txt', header=None)

X = data.iloc[:, :-1]
y = data.iloc[:, -1]

#split data into train and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [47]:
def init_params():
    W1 = np.random.rand(3, X_train.shape[1]) - 0.5
    b1 = np.random.rand(3, 1) - 0.5
    W2 = np.random.rand(3, 3) - 0.5
    b2 = np.random.rand(3, 1) - 0.5
    print(W1)
    print(b1)
    print(W2)
    print(b2)
    
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(Z, 0)

def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A
    
def forward_prop(W1, b1, W2, b2, X):
    Z1 = np.dot(X, W1.T)# + b1
    A1 = ReLU(Z1)
    Z2 = np.dot(A1, W2.T)# + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def ReLU_deriv(Z):
    return Z > 0

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1    
    W2 = W2 - alpha * dW2  
    b2 = b2 - alpha * db2    
    return W1, b1, W2, b2

In [48]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2

In [49]:
W1, b1, W2, b2 = gradient_descent(X_train, y_train, 0.10, 500)

[[ 0.40265641  0.0191094 ]
 [-0.33319317  0.0252508 ]
 [-0.11954128  0.3465874 ]]
[[ 0.03864918]
 [ 0.41706477]
 [-0.44071574]]
[[-0.01738691 -0.45159842 -0.32624097]
 [ 0.18405476  0.02711992 -0.03066849]
 [-0.01709199  0.44035469 -0.32101769]]
[[-0.08586909]
 [-0.21633777]
 [-0.00374464]]


ValueError: operands could not be broadcast together with shapes (82,3) (2,82) 